TYPE=VIEW
query=select max(`flight_management_system`.`customer`.`customerno`) AS `max_num` from `flight_management_system`.`customer`
md5=3a1417818254bf60b8a22b5c70802f84
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-01-02 17:47:00
create-version=1
source=SELECT max(customerno) max_num FROM customer
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select max(`flight_management_system`.`customer`.`customerno`) AS `max_num` from `flight_management_system`.`customer`
