TYPE=VIEW
query=select `flight_management_system`.`customer`.`customerno` AS `customerno` from `flight_management_system`.`customer` order by `flight_management_system`.`customer`.`customerno`
md5=c01cef206c55a199207277a73035d091
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2016-12-30 02:16:14
create-version=1
source=SELECT customerno FROM customer\nORDER BY customerno ASC
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `flight_management_system`.`customer`.`customerno` AS `customerno` from `flight_management_system`.`customer` order by `flight_management_system`.`customer`.`customerno`
