TYPE=VIEW
query=select `flight_management_system`.`airline`.`airlineno` AS `airlineno`,`flight_management_system`.`airline`.`airwayshortname` AS `airwayshortname`,`flight_management_system`.`airline`.`departurecity` AS `departurecity`,`flight_management_system`.`airline`.`arrivecity` AS `arrivecity`,`flight_management_system`.`airline`.`departuredate` AS `departuredate`,`flight_management_system`.`airline`.`departuretime` AS `departuretime` from `flight_management_system`.`airline`
md5=d47b2dbf04d6d91140f3d230725d96bd
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-01-01 07:09:13
create-version=1
source=SELECT airlineno, airwayshortname, departurecity, arrivecity, departuredate, departuretime\nFROM airline
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `flight_management_system`.`airline`.`airlineno` AS `airlineno`,`flight_management_system`.`airline`.`airwayshortname` AS `airwayshortname`,`flight_management_system`.`airline`.`departurecity` AS `departurecity`,`flight_management_system`.`airline`.`arrivecity` AS `arrivecity`,`flight_management_system`.`airline`.`departuredate` AS `departuredate`,`flight_management_system`.`airline`.`departuretime` AS `departuretime` from `flight_management_system`.`airline`
