TYPE=VIEW
query=select `flight_management_system`.`customertype`.`customertypename` AS `customertypename`,`flight_management_system`.`customertype`.`discountpercent` AS `discountpercent` from `flight_management_system`.`customertype`
md5=89e11b6deab5773d328fff2de4543e2e
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2017-01-01 10:08:43
create-version=1
source=SELECT customertypename, discountpercent FROM customertype
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `flight_management_system`.`customertype`.`customertypename` AS `customertypename`,`flight_management_system`.`customertype`.`discountpercent` AS `discountpercent` from `flight_management_system`.`customertype`
