TYPE=VIEW
query=select `flight_management_system`.`customertype`.`customertypename` AS `客户类型` from `flight_management_system`.`customertype`
md5=5a2496c306561d034cc866b7f330f20d
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2016-12-29 09:18:24
create-version=1
source=SELECT customertypename 客户类型 FROM customertype
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `flight_management_system`.`customertype`.`customertypename` AS `客户类型` from `flight_management_system`.`customertype`
